[compat]
	undergarden = true
	twilightforest = true
	toughasnails = true
	mowziesmobs = true
	irons_spellbooks = true
	immersiveengineering = true
	farmersdelight = true
	ecologics = true
	create = true
	cataclysm = true
	ars_nouveau = true
