#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 20 19:54:38 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryReimagined_r5.9.3.zip
